services:
    redis-server:
        image: 'redis'
        command: ["redis-server", "--save","1 1" ,"--protected-mode", "no"]
    node-app:
        build: ./
        image: 'docker.io/chudayini/visits:1.0'
        ports:
            - "8081:8081"